# Generated by Django 5.0.6 on 2024-06-13 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectDbId', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageHeight', models.PositiveIntegerField()),
                ('imageWidth', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, height_field=models.PositiveIntegerField(), null=True, upload_to='', width_field=models.PositiveIntegerField())),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inference.project')),
            ],
        ),
    ]
