version: '3.8'

services: 
    postgres:
        image: postgres:13
        restart: unless-stopped
        container_name: pgsql_db
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app_db
        ports:
            - 5432:5432
        # volumes:
        #     - torch_infer_data:/var/lib/postgesql/data

    adminer:
        image: adminer
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_SERVER: postgres
            ADMINER_DESIGN: dracula
        ports:
            - 8080:8080
        container_name: adminer
        
# volumes:
#     torch_infer_data:
